project_id = "mvlcefiygkzzewcdzsmj"

[functions.process-email-queue]
verify_jwt = true

[functions.integration-webhook]
verify_jwt = false

[functions.integration-oauth-start]
verify_jwt = true

[functions.integration-oauth-callback]
verify_jwt = false
