import type { ReactNode } from "react";

export type WebsiteToolGuide = {
  id: string;
  name: string;
  bestFor: string;
  time: string;
  recommendedAction: string;
  simplestSteps: string[];
  advancedTitle?: string;
  advancedWhen?: string;
  advancedSteps?: string[];
  note?: ReactNode;
};

export const websiteToolChecklist = [
  { id: "tools-copy-badge", label: "Copy branded PhotoBrief.ai badge embed" },
  { id: "tools-fallback-link", label: "Keep hosted intake link ready as fallback" },
  { id: "tools-pick-tool", label: "Pick the guide for my website tool" },
  { id: "tools-add-badge", label: "Add badge or button to one website page" },
  { id: "tools-test", label: "Submit one test lead from the live site" },
  { id: "tools-check-brief", label: "Confirm PhotoBrief creates the request" },
];

export const websiteToolGuides: WebsiteToolGuide[] = [
  {
    id: "any-site",
    name: "Any website",
    bestFor: "The fastest setup when you are not sure what builder your site uses.",
    time: "2 minutes",
    recommendedAction: "Add the branded PhotoBrief.ai badge where customers start quote, service, return, or photo requests.",
    simplestSteps: [
      "Open PhotoBrief → Website Intake.",
      "Copy the branded badge embed code. It includes the PhotoBrief.ai trust mark, a short customer explanation, and your hosted intake link.",
      "Open your website editor.",
      "Add the badge near the main customer action area, or use the hosted link behind a normal button if your site cannot embed custom HTML.",
      "Use clear surrounding copy: Get a quote, Request service, Start a return, or Send photos.",
      "Publish your site.",
      "Open the live site and submit one test request.",
    ],
    note: <>The badge is the best default because it keeps PhotoBrief branding and customer expectations consistent across websites. A working hosted link is the fallback when the site builder blocks embeds.</>,
  },
  {
    id: "wix",
    name: "Wix",
    bestFor: "Small service sites using Wix Editor or Wix Studio.",
    time: "3 minutes",
    recommendedAction: "Add the PhotoBrief.ai badge with an embed/custom code element, or link an existing Wix button as fallback.",
    simplestSteps: [
      "Open Wix and edit your site.",
      "Add an Embed / Custom Code element where the customer starts the request.",
      "Paste the PhotoBrief.ai badge embed from Website Intake.",
      "Resize the embed so the full badge and CTA are visible.",
      "If embeds are not available, click the existing button and paste your hosted intake link as the destination.",
      "Publish the site.",
      "Test from the live site, not only inside the editor.",
    ],
    advancedTitle: "If you already use a Wix form",
    advancedWhen: "Use this only if the existing form is important and you already know how it sends submissions.",
    advancedSteps: [
      "Keep the form fields simple: name, email, phone, request type, message, address.",
      "Send form submissions to PhotoBrief through Zapier, Make, or a webhook-capable automation.",
      "Use the Website Intake webhook URL from PhotoBrief.",
      "Send one test lead and confirm the right template is selected.",
    ],
  },
  {
    id: "squarespace",
    name: "Squarespace",
    bestFor: "Polished brochure sites, local service pages, and portfolio-style businesses.",
    time: "3 minutes",
    recommendedAction: "Use a Code block for the PhotoBrief.ai badge, or a button block/header button as fallback.",
    simplestSteps: [
      "Open Squarespace and edit the page where customers ask for help.",
      "Add a Code block near the main call to action.",
      "Paste the PhotoBrief.ai badge embed from Website Intake.",
      "Preview the page and confirm the badge, explanation, and CTA fit cleanly.",
      "If your plan or template blocks code, add a Button block and paste the hosted intake link.",
      "Save, publish, and test from the live site.",
    ],
    advancedTitle: "If you already use a Squarespace form",
    advancedWhen: "Use an automation tool only if you need to keep the existing form exactly as-is.",
    advancedSteps: [
      "Keep the existing form short.",
      "Connect form submissions through Zapier or Make.",
      "POST the lead data to the PhotoBrief Website Intake webhook URL.",
      "Map request type and message carefully so routing rules can work.",
      "Submit one test lead and check the created PhotoBrief request.",
    ],
  },
  {
    id: "wordpress",
    name: "WordPress",
    bestFor: "WordPress.com, WordPress block editor, and most custom WordPress sites.",
    time: "3 minutes",
    recommendedAction: "Add a Custom HTML block with the PhotoBrief.ai badge, or use a Button block as fallback.",
    simplestSteps: [
      "Open the WordPress dashboard.",
      "Edit the page customers use to contact you.",
      "Add a Custom HTML block where the request should begin.",
      "Paste the PhotoBrief.ai badge embed from Website Intake.",
      "Preview the page. If scripts/iframes are blocked, use a Button block and paste the hosted intake link.",
      "Update or publish the page.",
      "Open the live page and submit one test request.",
    ],
    advancedTitle: "If you use Contact Form 7, Gravity Forms, WPForms, or Fluent Forms",
    advancedWhen: "Use this if your form plugin already supports webhooks, Zapier, or Make.",
    advancedSteps: [
      "Create a short form with name, email, phone, request type, message, and address.",
      "Connect the form plugin to a webhook, Zapier, or Make.",
      "Use the PhotoBrief Website Intake webhook URL as the destination.",
      "Send data as JSON when possible.",
      "Run one test and confirm PhotoBrief creates the customer and request.",
    ],
  },
  {
    id: "elementor",
    name: "Elementor",
    bestFor: "WordPress sites built with Elementor pages or templates.",
    time: "2 minutes",
    recommendedAction: "Paste the badge embed into an HTML widget, or paste the hosted link into an Elementor Button element.",
    simplestSteps: [
      "Open the page in Elementor.",
      "Add an HTML widget near the customer action section.",
      "Paste the PhotoBrief.ai badge embed from Website Intake.",
      "Preview the page and confirm the badge is readable on desktop and mobile.",
      "If HTML embeds are not available, click the existing button and paste your hosted intake link into Link.",
      "Update the page.",
      "Test from the live page on your phone.",
    ],
    advancedTitle: "If you use Elementor forms",
    advancedWhen: "Use webhook automation only if your Elementor setup already includes form integrations.",
    advancedSteps: [
      "Keep the Elementor form short.",
      "Send submissions to PhotoBrief through webhook, Zapier, or Make.",
      "Map form fields to PhotoBrief fields.",
      "Test one submission and confirm routing works.",
    ],
  },
  {
    id: "webflow",
    name: "Webflow",
    bestFor: "Design-forward sites where a Webflow designer can update buttons and forms.",
    time: "3 minutes",
    recommendedAction: "Place the PhotoBrief.ai badge in an Embed element, or set a button/link block to the hosted intake URL.",
    simplestSteps: [
      "Open the Webflow Designer.",
      "Add an Embed element near the request call to action.",
      "Paste the PhotoBrief.ai badge embed from Website Intake.",
      "Publish and test the badge from the published domain.",
      "If embeds are not wanted, select the button, text link, or link block and paste the hosted intake link as the URL.",
      "Test from desktop and phone.",
    ],
    advancedTitle: "If you want to keep a Webflow form",
    advancedWhen: "Use this when the website already has a good Webflow form and you want it to trigger PhotoBrief automatically.",
    advancedSteps: [
      "Keep the Webflow form short and plain.",
      "Use Zapier, Make, or another automation tool after form submission.",
      "POST the lead data to the PhotoBrief Website Intake webhook URL.",
      "Map request type and message so rules can choose the right template.",
      "Run a live published-form test.",
    ],
  },
  {
    id: "shopify",
    name: "Shopify",
    bestFor: "Stores that also need returns, warranty photos, custom quotes, or service requests.",
    time: "3 minutes",
    recommendedAction: "Add the badge to a page/theme section, or add PhotoBrief as a menu item/button fallback.",
    simplestSteps: [
      "Open Shopify admin.",
      "Use a custom liquid/custom HTML section if your theme supports it, then paste the PhotoBrief.ai badge embed.",
      "Place the badge on a returns, warranty, service, or quote page.",
      "If your theme does not support custom embeds, add a menu item or button with the hosted intake link.",
      "Name it Request service, Start a return, Warranty photos, or Get a quote.",
      "Save and preview the live store.",
      "Submit one test request.",
    ],
    advancedTitle: "For returns or warranty workflows",
    advancedWhen: "Use separate PhotoBrief templates for different request types.",
    advancedSteps: [
      "Create templates for return photos, warranty photos, damaged item photos, or custom quote photos.",
      "Create routing rules using words like return, warranty, damaged, quote, or custom.",
      "Put the same hosted intake link anywhere customers start that workflow.",
      "Submit test leads for each request type.",
    ],
  },
  {
    id: "godaddy",
    name: "GoDaddy Websites + Marketing",
    bestFor: "Very simple local business websites.",
    time: "3 minutes",
    recommendedAction: "Use the hosted intake link behind an action button; add the badge only if custom code is available.",
    simplestSteps: [
      "Open GoDaddy and manage your website.",
      "Select Edit Website.",
      "Go to the section with the action button, or add a section that has one.",
      "Turn the action button on if needed.",
      "Set the action to link to a website or external URL.",
      "Paste your PhotoBrief hosted intake link.",
      "If your GoDaddy plan supports custom HTML, you can use the branded badge instead.",
      "Publish and test from the live site.",
    ],
    note: <>For most GoDaddy sites, do not overbuild this. A visible action button linked to PhotoBrief is the cleanest setup; the badge is a bonus when custom embeds are available.</>,
  },
  {
    id: "carrd",
    name: "Carrd",
    bestFor: "One-page service sites, landing pages, and link-in-bio style pages.",
    time: "2 minutes",
    recommendedAction: "Use an Embed element for the badge, or a button that opens the hosted PhotoBrief intake link.",
    simplestSteps: [
      "Open Carrd and edit the site.",
      "Add an Embed element if your plan supports embeds.",
      "Paste the PhotoBrief.ai badge embed from Website Intake.",
      "If embeds are not available, add a Button element and set the URL to your hosted intake link.",
      "Use direct text like Get a quote or Send photos.",
      "Publish changes.",
      "Open the live page on your phone and submit one test request.",
    ],
    advancedTitle: "If you have Carrd Pro Plus and use a custom form",
    advancedWhen: "Use this only when you need the Carrd form itself to submit directly into PhotoBrief.",
    advancedSteps: [
      "Create a custom form.",
      "Set the form to Send to URL.",
      "Paste the PhotoBrief Website Intake webhook URL.",
      "Use POST or AJAX with JSON when available.",
      "Name fields simply: name, email, phone, request_type, message, address.",
      "Submit one live test and confirm PhotoBrief creates the request.",
    ],
  },
  {
    id: "zapier-make",
    name: "Zapier / Make bridge",
    bestFor: "Keeping an existing form while still triggering PhotoBrief automatically.",
    time: "10–15 minutes",
    recommendedAction: "Use only when a badge or hosted link is not enough.",
    simplestSteps: [
      "Start with the website form trigger: new form submission, new lead, or new contact.",
      "Add an action that sends a webhook request.",
      "Use the PhotoBrief Website Intake webhook URL.",
      "Send fields as JSON when possible.",
      "Map name, email, phone, request_type, message, and address.",
      "Turn on the Zap or scenario.",
      "Submit one real test from the website and check PhotoBrief.",
    ],
    note: <>If a business owner is not already comfortable with Zapier or Make, skip this and use the branded badge or hosted link first.</>,
  },
];
