import type { ReactNode } from "react";

export type WebsiteToolGuide = {
  id: string;
  name: string;
  bestFor: string;
  time: string;
  recommendedAction: string;
  simplestSteps: string[];
  advancedTitle?: string;
  advancedWhen?: string;
  advancedSteps?: string[];
  note?: ReactNode;
};

export const websiteToolChecklist = [
  { id: "tools-copy-link", label: "Copy hosted Website Intake link" },
  { id: "tools-pick-tool", label: "Pick the guide for my website tool" },
  { id: "tools-add-button", label: "Add or update one website button" },
  { id: "tools-test", label: "Submit one test lead from the live site" },
  { id: "tools-check-brief", label: "Confirm PhotoBrief creates the request" },
];

export const websiteToolGuides: WebsiteToolGuide[] = [
  {
    id: "any-site",
    name: "Any website",
    bestFor: "The fastest setup when you are not sure what builder your site uses.",
    time: "2 minutes",
    recommendedAction: "Add one button or link called “Get a quote” or “Request service.”",
    simplestSteps: [
      "Open PhotoBrief → Website Intake.",
      "Copy your hosted intake link.",
      "Open your website editor.",
      "Find the main button customers already use, like Contact us, Get a quote, Book now, or Request service.",
      "Paste the PhotoBrief link as that button’s destination.",
      "Publish your site.",
      "Open the live site and submit one test request.",
    ],
    note: <>Start here if the business owner is setting this up themselves. A working link beats a complicated integration every time.</>,
  },
  {
    id: "wix",
    name: "Wix",
    bestFor: "Small service sites using Wix Editor or Wix Studio.",
    time: "3 minutes",
    recommendedAction: "Link an existing button to your hosted PhotoBrief intake form.",
    simplestSteps: [
      "Open Wix and edit your site.",
      "Click the button customers should use, like Get a quote or Request service.",
      "Click the link icon.",
      "Choose Web address or External URL.",
      "Paste your PhotoBrief hosted intake link.",
      "Click Done, then Publish.",
      "Test from the live site, not only inside the editor.",
    ],
    advancedTitle: "If you already use a Wix form",
    advancedWhen: "Use this only if the existing form is important and you already know how it sends submissions.",
    advancedSteps: [
      "Keep the form fields simple: name, email, phone, request type, message, address.",
      "Send form submissions to PhotoBrief through Zapier, Make, or a webhook-capable automation.",
      "Use the Website Intake webhook URL from PhotoBrief.",
      "Send one test lead and confirm the right template is selected.",
    ],
  },
  {
    id: "squarespace",
    name: "Squarespace",
    bestFor: "Polished brochure sites, local service pages, and portfolio-style businesses.",
    time: "3 minutes",
    recommendedAction: "Use a button block, header button, or navigation link that points to PhotoBrief.",
    simplestSteps: [
      "Open Squarespace and edit the page where customers ask for help.",
      "Add or select a Button block, header button, or navigation link.",
      "Set the link type to URL or external link.",
      "Paste your PhotoBrief hosted intake link.",
      "Use clear button text: Get a quote, Request service, or Send photos.",
      "Save, publish, and test from the live site.",
    ],
    advancedTitle: "If you already use a Squarespace form",
    advancedWhen: "Use an automation tool only if you need to keep the existing form exactly as-is.",
    advancedSteps: [
      "Keep the existing form short.",
      "Connect form submissions through Zapier or Make.",
      "POST the lead data to the PhotoBrief Website Intake webhook URL.",
      "Map request type and message carefully so routing rules can work.",
      "Submit one test lead and check the created PhotoBrief request.",
    ],
  },
  {
    id: "wordpress",
    name: "WordPress",
    bestFor: "WordPress.com, WordPress block editor, and most custom WordPress sites.",
    time: "3 minutes",
    recommendedAction: "Add a Button block and paste the hosted intake link.",
    simplestSteps: [
      "Open the WordPress dashboard.",
      "Edit the page customers use to contact you.",
      "Add a Button block, or select the existing call-to-action button.",
      "Set the button text to Get a quote, Request service, or Send photos.",
      "Paste your PhotoBrief hosted intake link into the button link field.",
      "Update or publish the page.",
      "Open the live page and submit one test request.",
    ],
    advancedTitle: "If you use Contact Form 7, Gravity Forms, WPForms, or Fluent Forms",
    advancedWhen: "Use this if your form plugin already supports webhooks, Zapier, or Make.",
    advancedSteps: [
      "Create a short form with name, email, phone, request type, message, and address.",
      "Connect the form plugin to a webhook, Zapier, or Make.",
      "Use the PhotoBrief Website Intake webhook URL as the destination.",
      "Send data as JSON when possible.",
      "Run one test and confirm PhotoBrief creates the customer and request.",
    ],
  },
  {
    id: "elementor",
    name: "Elementor",
    bestFor: "WordPress sites built with Elementor pages or templates.",
    time: "2 minutes",
    recommendedAction: "Paste the hosted intake link into an Elementor Button element.",
    simplestSteps: [
      "Open the page in Elementor.",
      "Click the button customers should use.",
      "In the button settings, find Link.",
      "Paste your PhotoBrief hosted intake link.",
      "Use simple text like Get a quote or Request service.",
      "Update the page.",
      "Test from the live page on your phone.",
    ],
    advancedTitle: "If you use Elementor forms",
    advancedWhen: "Use webhook automation only if your Elementor setup already includes form integrations.",
    advancedSteps: [
      "Keep the Elementor form short.",
      "Send submissions to PhotoBrief through webhook, Zapier, or Make.",
      "Map form fields to PhotoBrief fields.",
      "Test one submission and confirm routing works.",
    ],
  },
  {
    id: "webflow",
    name: "Webflow",
    bestFor: "Design-forward sites where a Webflow designer can update buttons and forms.",
    time: "3 minutes",
    recommendedAction: "Set a Webflow button or link block to your hosted intake URL.",
    simplestSteps: [
      "Open the Webflow Designer.",
      "Select the button, text link, or link block customers should click.",
      "Open Element settings / Link settings.",
      "Choose URL or external URL.",
      "Paste your PhotoBrief hosted intake link.",
      "Publish the site.",
      "Test from the published domain.",
    ],
    advancedTitle: "If you want to keep a Webflow form",
    advancedWhen: "Use this when the website already has a good Webflow form and you want it to trigger PhotoBrief automatically.",
    advancedSteps: [
      "Keep the Webflow form short and plain.",
      "Use Zapier, Make, or another automation tool after form submission.",
      "POST the lead data to the PhotoBrief Website Intake webhook URL.",
      "Map request type and message so rules can choose the right template.",
      "Run a live published-form test.",
    ],
  },
  {
    id: "shopify",
    name: "Shopify",
    bestFor: "Stores that also need returns, warranty photos, custom quotes, or service requests.",
    time: "3 minutes",
    recommendedAction: "Add PhotoBrief as a menu item, page button, or theme button.",
    simplestSteps: [
      "Open Shopify admin.",
      "Go to Content → Menus if you want a navigation link, or Online Store → Themes if you want a page/theme button.",
      "Add a menu item or edit the button customers should use.",
      "Name it Request service, Start a return, Warranty photos, or Get a quote.",
      "Paste your PhotoBrief hosted intake link as the external URL.",
      "Save and preview the live store.",
      "Submit one test request.",
    ],
    advancedTitle: "For returns or warranty workflows",
    advancedWhen: "Use separate PhotoBrief templates for different request types.",
    advancedSteps: [
      "Create templates for return photos, warranty photos, damaged item photos, or custom quote photos.",
      "Create routing rules using words like return, warranty, damaged, quote, or custom.",
      "Put the same hosted intake link anywhere customers start that workflow.",
      "Submit test leads for each request type.",
    ],
  },
  {
    id: "godaddy",
    name: "GoDaddy Websites + Marketing",
    bestFor: "Very simple local business websites.",
    time: "3 minutes",
    recommendedAction: "Edit an action button and point it to PhotoBrief.",
    simplestSteps: [
      "Open GoDaddy and manage your website.",
      "Select Edit Website.",
      "Go to the section with the action button, or add a section that has one.",
      "Turn the action button on if needed.",
      "Set the action to link to a website or external URL.",
      "Paste your PhotoBrief hosted intake link.",
      "Publish and test from the live site.",
    ],
    note: <>For most GoDaddy sites, do not overbuild this. A visible action button linked to PhotoBrief is the cleanest setup.</>,
  },
  {
    id: "carrd",
    name: "Carrd",
    bestFor: "One-page service sites, landing pages, and link-in-bio style pages.",
    time: "2 minutes",
    recommendedAction: "Use a button that opens the hosted PhotoBrief intake link.",
    simplestSteps: [
      "Open Carrd and edit the site.",
      "Add a Button element or select the existing call-to-action button.",
      "Set the button URL to your PhotoBrief hosted intake link.",
      "Use direct text like Get a quote or Send photos.",
      "Publish changes.",
      "Open the live page on your phone and submit one test request.",
    ],
    advancedTitle: "If you have Carrd Pro Plus and use a custom form",
    advancedWhen: "Use this only when you need the Carrd form itself to submit directly into PhotoBrief.",
    advancedSteps: [
      "Create a custom form.",
      "Set the form to Send to URL.",
      "Paste the PhotoBrief Website Intake webhook URL.",
      "Use POST or AJAX with JSON when available.",
      "Name fields simply: name, email, phone, request_type, message, address.",
      "Submit one live test and confirm PhotoBrief creates the request.",
    ],
  },
  {
    id: "zapier-make",
    name: "Zapier / Make bridge",
    bestFor: "Keeping an existing form while still triggering PhotoBrief automatically.",
    time: "10–15 minutes",
    recommendedAction: "Use only when a hosted link is not enough.",
    simplestSteps: [
      "Start with the website form trigger: new form submission, new lead, or new contact.",
      "Add an action that sends a webhook request.",
      "Use the PhotoBrief Website Intake webhook URL.",
      "Send fields as JSON when possible.",
      "Map name, email, phone, request_type, message, and address.",
      "Turn on the Zap or scenario.",
      "Submit one real test from the website and check PhotoBrief.",
    ],
    note: <>If a business owner is not already comfortable with Zapier or Make, skip this and use the hosted link first.</>,
  },
];
