import type { Config } from "tailwindcss";

export default {
  future: {
    hoverOnlyWhenSupported: true,
  },
  
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        display: [
          '"Bricolage Grotesque"',
          '"Inter"',
          "system-ui",
          "sans-serif",
        ],
        sans: [
          '"Inter"',
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          "system-ui",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        rounded: [
          "ui-rounded",
          '"SF Pro Rounded"',
          '"Nunito"',
          "system-ui",
          "sans-serif",
        ],
        mono: [
          '"Geist Mono"',
          "ui-monospace",
          '"SF Mono"',
          "Menlo",
          "Monaco",
          '"Cascadia Code"',
          '"Roboto Mono"',
          "monospace",
        ],
      },
      borderWidth: {
        hairline: "0.5px",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.32, 0.72, 0, 1)",
        "spring-snappy": "cubic-bezier(0.22, 1, 0.36, 1)",
        "spring-gentle": "cubic-bezier(0.4, 0, 0.2, 1.2)",
        "ease-out-quart": "cubic-bezier(0.165, 0.84, 0.44, 1)",
      },
      transitionDuration: {
        quick: "180ms",
        standard: "260ms",
        slow: "380ms",
      },
      colors: {
        // ── Apple HIG semantic groups ──
        label: {
          DEFAULT: "hsl(var(--label))",
          secondary: "hsl(var(--label-secondary) / var(--label-secondary-alpha))",
          tertiary: "hsl(var(--label-tertiary) / var(--label-tertiary-alpha))",
          quaternary: "hsl(var(--label-quaternary) / var(--label-quaternary-alpha))",
        },
        separator: {
          DEFAULT: "hsl(var(--separator))",
          opaque: "hsl(var(--opaque-separator))",
        },
        fill: {
          DEFAULT: "hsl(var(--system-fill))",
          secondary: "hsl(var(--secondary-system-fill))",
          tertiary: "hsl(var(--tertiary-system-fill))",
          quaternary: "hsl(var(--quaternary-system-fill))",
        },
        systemBackground: {
          DEFAULT: "hsl(var(--system-background))",
          secondary: "hsl(var(--secondary-system-background))",
          tertiary: "hsl(var(--tertiary-system-background))",
          grouped: "hsl(var(--system-grouped-background))",
          "grouped-secondary": "hsl(var(--secondary-system-grouped-background))",
          "grouped-tertiary": "hsl(var(--tertiary-system-grouped-background))",
        },
        system: {
          blue: "hsl(var(--system-blue))",
          indigo: "hsl(var(--system-indigo))",
          purple: "hsl(var(--system-purple))",
          pink: "hsl(var(--system-pink))",
          red: "hsl(var(--system-red))",
          orange: "hsl(var(--system-orange))",
          yellow: "hsl(var(--system-yellow))",
          green: "hsl(var(--system-green))",
          mint: "hsl(var(--system-mint))",
          teal: "hsl(var(--system-teal))",
          cyan: "hsl(var(--system-cyan))",
          brown: "hsl(var(--system-brown))",
        },
        gray: {
          1: "hsl(var(--system-gray-1))",
          2: "hsl(var(--system-gray-2))",
          3: "hsl(var(--system-gray-3))",
          4: "hsl(var(--system-gray-4))",
          5: "hsl(var(--system-gray-5))",
          6: "hsl(var(--system-gray-6))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        brand: {
          navy: "hsl(var(--brand-navy))",
          "navy-foreground": "hsl(var(--brand-navy-foreground))",
          amber: "hsl(var(--brand-amber))",
          "amber-light": "hsl(var(--brand-amber-light))",
          "amber-hover": "hsl(var(--brand-amber-hover))",
          cream: "hsl(var(--brand-cream))",
          "cream-warm": "hsl(var(--brand-cream-warm))",
          graphite: "hsl(var(--brand-graphite))",
          lens: "hsl(var(--brand-lens))",
          flash: "hsl(var(--brand-flash))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-subtle": "var(--gradient-subtle)",
        "gradient-brand": "var(--gradient-brand)",
        "gradient-radial-glow": "var(--gradient-radial-glow)",
        "ambient-sky": "var(--ambient-sky)",
        "ambient-mesh": "var(--ambient-mesh)",
      },
      backdropBlur: {
        glass: "16px",
        "glass-lg": "24px",
      },
      boxShadow: {
        "elev-sm": "var(--shadow-sm)",
        "elev-md": "var(--shadow-md)",
        "elev-lg": "var(--shadow-lg)",
        glow: "var(--shadow-glow)",
        brand: "var(--shadow-brand)",
        glass: "var(--glass-shadow)",
        "glass-lg": "var(--glass-shadow-lg)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(4px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "lift-in": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "bubble-in": { from: { opacity: "0", transform: "translateY(6px) scale(.98)" }, to: { opacity: "1", transform: "translateY(0) scale(1)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "lift-in": "lift-in 0.36s cubic-bezier(0.32,0.72,0,1) both",
        "bubble-in": "bubble-in 0.24s cubic-bezier(0.32,0.72,0,1) both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
