import { useEffect } from "react";

/**
 * SEOHead — sets per-route <title>, description, canonical, robots,
 * Open Graph/Twitter tags, and JSON-LD without pulling in react-helmet.
 *
 * Search/answer-engine crawlers read these from prerendered HTML generated by
 * scripts/prerender.mjs. Real visitors also get correct tags after SPA route
 * transitions.
 */
interface SEOHeadProps {
  title: string;
  description: string;
  /** Path-only canonical, e.g. "/pricing". Origin is added automatically. */
  canonicalPath: string;
  /** Optional JSON-LD object — serialized into a single <script> tag. */
  jsonLd?: Record<string, unknown> | Record<string, unknown>[];
  /** Set true for auth/app/tokenized pages that should not appear in search. */
  noindex?: boolean;
  ogImage?: string;
  ogType?: "website" | "article" | "product";
  twitterCard?: "summary" | "summary_large_image";
  /** Override OG/Twitter title (defaults to title). */
  ogTitle?: string;
  /** Override OG/Twitter description (defaults to description). */
  ogDescription?: string;
}

const ORIGIN = "https://photobrief.ai";
const DEFAULT_OG_IMAGE = "https://photobrief.ai/og-image.png";

function setMeta(name: string, content: string, attr: "name" | "property" = "name") {
  let el = document.head.querySelector<HTMLMetaElement>(`meta[${attr}="${name}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute(attr, name);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}

function setLinkCanonical(href: string) {
  let el = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');
  if (!el) {
    el = document.createElement("link");
    el.rel = "canonical";
    document.head.appendChild(el);
  }
  el.href = href;
}

function setJsonLd(id: string, payload: SEOHeadProps["jsonLd"]) {
  document.head.querySelector(`script[data-seo-jsonld="${id}"]`)?.remove();
  if (!payload) return;
  const script = document.createElement("script");
  script.type = "application/ld+json";
  script.dataset.seoJsonld = id;
  script.textContent = JSON.stringify(payload);
  document.head.appendChild(script);
}

export function SEOHead({
  title,
  description,
  canonicalPath,
  jsonLd,
  noindex = false,
  ogImage = DEFAULT_OG_IMAGE,
  ogType = "website",
  twitterCard = "summary_large_image",
  ogTitle,
  ogDescription,
}: SEOHeadProps) {
  useEffect(() => {
    const canonical = `${ORIGIN}${canonicalPath === "/" ? "" : canonicalPath}`;
    const imageUrl = ogImage.startsWith("http") ? ogImage : `${ORIGIN}${ogImage}`;
    const socialTitle = ogTitle ?? title;
    const socialDesc = ogDescription ?? description;

    document.title = title;
    setMeta("description", description);
    setMeta("robots", noindex ? "noindex, nofollow, noarchive" : "index, follow, max-image-preview:large");
    setMeta("googlebot", noindex ? "noindex, nofollow, noarchive" : "index, follow, max-image-preview:large");
    setLinkCanonical(canonical);

    // Open Graph + Twitter
    setMeta("og:title", socialTitle, "property");
    setMeta("og:description", socialDesc, "property");
    setMeta("og:url", canonical, "property");
    setMeta("og:image", imageUrl, "property");
    setMeta("og:image:width", "1200", "property");
    setMeta("og:image:height", "630", "property");
    setMeta("og:type", ogType, "property");
    setMeta("og:site_name", "PhotoBrief", "property");
    setMeta("twitter:title", socialTitle);
    setMeta("twitter:description", socialDesc);
    setMeta("twitter:image", imageUrl);
    setMeta("twitter:card", twitterCard);
    setMeta("twitter:site", "@photobriefai");

    setJsonLd(canonicalPath, jsonLd);
  }, [title, description, canonicalPath, jsonLd, noindex, ogImage, ogType, twitterCard, ogTitle, ogDescription]);

  return null;
}
