// Request builder draft types — generated by a saved guide or AI, edited in
// the preview, then turned into a real PhotoBriefRequest on Create.
import type { ContextQuestion, GuideStep, PhotoGuide } from "@/types/photobrief";
import { STANDARD_PHOTO_ISSUE_TYPES } from "@/config/photoAssessment";

export interface ReadinessRule {
  id: string;
  /** Plain-language description ("All required photos captured", etc.) */
  description: string;
  weight: number; // contribution to readiness score 0-100
}

export interface RequestDraft {
  /** Stable id used while editing in the UI. */
  draftId: string;
  /** Source — informs the Save-as-Guide behavior. */
  source: "template" | "ai" | "blank";
  /** Original prompt if source = "ai". */
  prompt?: string;
  /** Saved guide id if source = template. */
  baseGuideId?: string;

  title: string;
  introMessage: string;
  completionMessage: string;
  steps: GuideStep[];
  questions: ContextQuestion[];
  readinessRules: ReadinessRule[];

  recipientName: string;
  recipientContact: string;
}

export function createDefaultStep(orderIndex = 0): GuideStep {
  return {
    id: `step_${Date.now()}_${orderIndex}`,
    orderIndex,
    title: orderIndex === 0 ? "Photo I need" : "Another photo I need",
    instructions: "Tell the customer exactly what to capture and any tips that will help them get it right.",
    shotType: "photo",
    overlayType: "full_area",
    aiChecks: [...STANDARD_PHOTO_ISSUE_TYPES],
    required: true,
  };
}

export function createBlankDraft(prefill?: Partial<Pick<RequestDraft, "recipientName" | "recipientContact">>): RequestDraft {
  const steps = [createDefaultStep(0)];
  return {
    draftId: `draft_${Date.now()}`,
    source: "blank",
    title: "New photo request",
    introMessage: "Hi! Please follow the steps below and send the requested photos. It should only take a minute or two.",
    completionMessage: "Thanks — your photos have been sent.",
    steps,
    questions: [],
    readinessRules: defaultReadinessRules(steps.length),
    recipientName: prefill?.recipientName ?? "",
    recipientContact: prefill?.recipientContact ?? "",
  };
}

/** Build a draft from an existing saved PhotoGuide template. */
export function draftFromGuide(guide: PhotoGuide): RequestDraft {
  return {
    draftId: `draft_${Date.now()}`,
    source: "template",
    baseGuideId: guide.id,
    title: guide.name,
    introMessage: `Hi! Please follow the steps below for ${guide.name}. It should only take a minute or two.`,
    completionMessage:
      "Thanks! Your photos are on the way. We'll get back to you shortly.",
    steps: guide.steps.map((s) => ({ ...s, aiChecks: [...STANDARD_PHOTO_ISSUE_TYPES] })),
    questions: guide.questions.map((q) => ({ ...q })),
    readinessRules: defaultReadinessRules(guide.steps.length),
    recipientName: "",
    recipientContact: "",
  };
}

export function defaultReadinessRules(stepCount: number): ReadinessRule[] {
  return [
    {
      id: "rr_required",
      description: "All required photos captured",
      weight: 60,
    },
    {
      id: "rr_quality",
      description: `At least ${Math.max(1, Math.ceil(stepCount * 0.7))} photos pass AI quality checks`,
      weight: 25,
    },
    {
      id: "rr_questions",
      description: "All required context questions answered",
      weight: 15,
    },
  ];
}
