// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Build a stub client whose methods reject with a clear error instead of
 * crashing module-init when env vars are missing from the build. This keeps
 * React mounting so the ErrorBoundary can render a real fallback UI rather
 * than a blank white screen.
 */
function buildStubClient(): SupabaseClient<Database> {
  const message =
    "[supabase] VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY missing at build time — re-publish the project so the latest .env is baked into the bundle.";
  // Surface once, loudly, in the console so the diagnosis is obvious.
  // eslint-disable-next-line no-console
  console.error(message);

  const reject = () => Promise.reject(new Error(message));
  const queryHandler: ProxyHandler<object> = {
    get: () => new Proxy(() => {}, queryHandler),
    apply: () => new Proxy(() => {}, queryHandler),
  };
  const thenable = {
    then: (_: unknown, onRejected?: (reason: unknown) => unknown) =>
      Promise.resolve().then(() => (onRejected ? onRejected(new Error(message)) : Promise.reject(new Error(message)))),
  };
  const stub: any = {
    auth: {
      getSession: reject,
      getUser: reject,
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      signInWithPassword: reject,
      signInWithOAuth: reject,
      signUp: reject,
      signOut: reject,
      resetPasswordForEmail: reject,
      updateUser: reject,
      exchangeCodeForSession: reject,
    },
    from: () => new Proxy(thenable, queryHandler),
    rpc: reject,
    functions: { invoke: reject },
    storage: { from: () => ({ upload: reject, getPublicUrl: () => ({ data: { publicUrl: "" } }), createSignedUrl: reject, remove: reject }) },
    channel: () => ({ on: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }), subscribe: () => ({ unsubscribe: () => {} }) }),
    removeChannel: () => {},
  };
  return stub as SupabaseClient<Database>;
}

export const supabase: SupabaseClient<Database> =
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : buildStubClient();
